[package]
name = "nftver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paq = "0.4.0"
qrcode = "0.12.0"
